policies:
  - path: ""
    allowedrange:
      - 08:00 - 21:30
  - path: youtube.com
    allowedrange:
      - 20:00 - 21:30
  - path: www.youtube.com
    allowedrange:
      - 20:00 - 21:30
  - path: artofproblemsolving.com/community
    allowedrange:
      - 20:00 - 23:00
  - path: dnvodcdn.me
    allowedrange:
      - 21:00 - 21:01
  - path: baidu.com
    allowedrange:
      - 21:00 - 21:01
  - path: m.tv
  - path: dnvodcdn.me
logs:
  provider: console
  config:
    url: shawn:password@/clarity
  skip-logging:
    - play.google.com/log
    - latex.artofproblemsolving.com
    - cdn.artofproblemsolving.com
    - avatar.artofproblemsolving.com
    - notion.so
    - safebrowsing.googleapis.com
    - cloudsink.net
    - www.googleapis.com
    - client6.google.com
    - api.apple-cloudkit.com
    - docs.google.com
skip-proxy:
  - icloud.com
  - icloud.com.cn
  - api.apple-cloudkit.com
  - apple.com
  - mzstatic.com
  - cdn-apple.com
  - corp.google.com
  - zoom.us
